language: ruby
rvm:
  - 2.4.7
  - 2.5.6
  - 2.6.4
before_install:
  - gem update --system
  - gem install bundler
cache: bundler
sudo: false
fast_finish: true
env:
  - SKIP_INTEGRATION=true
notifications:
  email:
    on_success: always
    on_failure: always
