language: ruby
rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
  - 2.7.0
before_install:
  - gem update --system
  - gem install bundler
cache: bundler
sudo: false
fast_finish: true
env:
  global:
    - PAYSAFE_ACCOUNT_NUMBER=test
    - PAYSAFE_API_KEY=test
    - PAYSAFE_API_SECRET=test
    - PAYSAFE_SUT_API_KEY=test
    - PAYSAFE_SUT_API_SECRET=test
    - PAYSAFE_UNITY_API_KEY=test
    - PAYSAFE_UNITY_API_SECRET=test
    - PAYSAFE_UNITY_SUT_API_KEY=test
    - PAYSAFE_UNITY_SUT_API_SECRET=test
notifications:
  email:
    on_success: always
    on_failure: always
